version: 0.1
component: build
timeoutInSeconds: 20000
runAs: root
shell: bash
env:
  exportedVariables:
   - version
steps:

  - type: Command
    name: "building spark in local"
    command: |
      ./build/mvn -DskipTests clean package
      top -b -n 1
#   - type: Command
#     name: "Running tests"
#     command: |
#       ./dev/run-tests
  - type: Command
    name: "run the Pi example locally"
    command: |
      top -b -n 1
      ./bin/run-example SparkPi
  - type: Command
    name: "genearte large file"
    command: |
      dd if=/dev/zero of=sample.psd count=100000 bs=100000
      ls -larth
      
  
      
